[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://garden-production-1bb1.up.railway.app"
DB_CONNECTION = "sqlite"
LOG_CHANNEL = "errorlog"
SESSION_DRIVER = "cookie"
CACHE_DRIVER = "array"
